import * as XLSX from "xlsx";
import { saveAs } from "file-saver";
import { ExportCard } from "./types";
import { generateExportFilename } from "./formatters";

/**
 * Generate and download an Excel file with missing cards
 */
export function generateMissingCardsExcel(
  cards: ExportCard[],
  setName: string
): void {
  // Create worksheet data
  const headers = [
    "Card Name",
    "Card Number",
    "Rarity",
    "Variant",
  ];

  const data = cards.map((card) => [
    card.name,
    card.cardNumber,
    card.rarity,
    card.variant,
  ]);

  // Combine headers and data
  const worksheetData = [headers, ...data];

  // Create worksheet
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths
  const colWidths = [
    { wch: 30 }, // Card Name
    { wch: 12 }, // Card Number
    { wch: 22 }, // Rarity
    { wch: 15 }, // Variant
  ];
  worksheet["!cols"] = colWidths;

  // Create workbook and add the worksheet
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Missing Cards");

  // Add a summary sheet
  const summaryData = [
    ["BinderDex - Missing Cards Export"],
    [],
    ["Set Name", setName],
    ["Total Missing", cards.length.toString()],
    ["Export Date", new Date().toLocaleDateString()],
    [],
    ["Generated by BinderDex - https://binderdex.com"],
  ];
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  summarySheet["!cols"] = [{ wch: 20 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

  // Generate Excel file
  const excelBuffer = XLSX.write(workbook, {
    bookType: "xlsx",
    type: "array",
  });

  // Create blob and download
  const blob = new Blob([excelBuffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const filename = generateExportFilename(setName, "xlsx");
  saveAs(blob, filename);
}
